/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoBasic: typeof import('./.vitepress/theme/components/Demo/Basic.vue')['default']
    DemoBatch: typeof import('./.vitepress/theme/components/Demo/Batch.vue')['default']
    DemoDeclarative: typeof import('./.vitepress/theme/components/Demo/Declarative.vue')['default']
    DemoFallback: typeof import('./.vitepress/theme/components/Demo/Fallback.vue')['default']
    DemoGettingStarted: typeof import('./.vitepress/theme/components/Demo/GettingStarted.vue')['default']
    DemoHitl: typeof import('./.vitepress/theme/components/Demo/Hitl.vue')['default']
    DemoIntro: typeof import('./.vitepress/theme/components/Demo/Intro.vue')['default']
    DemoLoop: typeof import('./.vitepress/theme/components/Demo/Loop.vue')['default']
    DemoParallel: typeof import('./.vitepress/theme/components/Demo/Parallel.vue')['default']
    DemoProgrammatic: typeof import('./.vitepress/theme/components/Demo/Programmatic.vue')['default']
    DemoRetry: typeof import('./.vitepress/theme/components/Demo/Retry.vue')['default']
    DemoSteps: typeof import('./.vitepress/theme/components/Demo/Steps.vue')['default']
    DemoVisualization: typeof import('./.vitepress/theme/components/Demo/Visualization.vue')['default']
    Diagram: typeof import('./.vitepress/theme/components/Diagram.vue')['default']
    EdgeLoopback: typeof import('./.vitepress/theme/components/Edge/Loopback.vue')['default']
    Flow: typeof import('./.vitepress/theme/components/Flow.vue')['default']
    NodeDefault: typeof import('./.vitepress/theme/components/Node/Default.vue')['default']
    NodeInput: typeof import('./.vitepress/theme/components/Node/Input.vue')['default']
    NodeNode: typeof import('./.vitepress/theme/components/Node/Node.vue')['default']
    NodeOutput: typeof import('./.vitepress/theme/components/Node/Output.vue')['default']
    NodeStatus: typeof import('./.vitepress/theme/components/Node/Status.vue')['default']
    Stepper: typeof import('./.vitepress/theme/components/Stepper.vue')['default']
  }
}
